const styles = {
	screen: {
	  display: "flex",
	  flexDirection: "column",
	  alignItems: "center",
	  backgroundColor: "#ffffff",
	  minHeight: "100%",
	},
	frame2: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		width: 393,
		paddingVertical: 5,    
		height: 150,
	  },
	backButton: {
	  fontSize: 20,
	  color: "#473b3b",
	},
	title: {
	  fontFamily: "Pretendard-ExtraBold",
	  fontSize: 16,
	  fontWeight: "800",
	  color: "#473b3b",
	  textAlign: "center",
	  width: 80,
	},
	frame3: {
	  flexDirection: "column",
	  alignItems: "flex-start",
	  paddingVertical: 10,
	  paddingHorizontal: 20,
	  width: 393,
	  marginBottom: 20,
	},
	sectionTitle: {
	  fontSize: 20,
	  fontWeight: "700",
	  fontFamily: "Roboto-Bold",
	  borderBottomWidth: 1,
	  borderBottomColor: "#d9d9d9",
	  borderStyle: "dashed",
	  paddingBottom: 15,
	  width: 352,
	  marginBottom: 15,
	  color: "#000000",
	  paddingLeft: 10, 
	  borderBottomWidth: 1,      
 	  borderBottomColor: "#d9d9d9", 
  	  borderStyle: "solid",  	
	},
	button: {
	  fontSize: 13,
	  fontWeight: "400",
	  fontFamily: "Roboto-Regular",
	  backgroundColor: "#ffffff",
	  borderRadius: 15,
	  paddingVertical: 8,
	  paddingHorizontal: 24,
	  width: 125,
	  textAlign: "left",
	  color: "#000000",
	  marginBottom: 8,   // 버튼 사이 간격
	},
	footer: {
	  flexDirection: "column",
	  alignItems: "center",
	  justifyContent: "flex-end",
	  flexGrow: 1,
	  padding: 100,
	  backgroundColor: "#ffffff",
	  width: "100%",
	},
	teamProject: {
	  fontFamily: "Inter-Medium",
	  fontSize: 14,
	  fontWeight: "500",
	  color: "#d0d0d0",
	  textAlign: "center",
	  marginBottom: 5,
	},
	footerText: {
	  fontFamily: "Inter-Medium",
	  fontSize: 14,
	  fontWeight: "500",
	  color: "#cacaca",
	  textAlign: "center",
	},
  };
  
  export default styles;
  